name: Create Monthly Ticket

on:
  schedule:
    # Runs at 00:00 UTC on the 1st of every other month
    # For example: January 1st, March 1st, May 1st, etc.
    - cron: '0 0 1 */2 *' 

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write # Required permission to create issues
    steps:
      - name: Create monthly maintenance issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Automated Ticket -  Update MTG decks
          LABELS: MTG
          BODY: |
            - [ ] Vintage
            - [ ] Legacy
            - [ ] Premodern
            - [ ] Modern
            - [ ] Pioneer
            - [ ] Standard
            - [ ] Pauper
            - [ ] Oathbreaker
            - [ ] Ice Age Block
            - [ ] Mirage Block
            - [ ] Tempest Block
            - [ ] Urza\'s Block
            - [ ] Masques Block
            - [ ] Invasion Block
            - [ ] Odyssey Block
            - [ ] Onslaught Block
            - [ ] Mirrodin Block
            - [ ] Kamigawa Block
            - [ ] Ravnica Block
            - [ ] Time Spiral Block
            - [ ] Pauper Commander
            - [ ] Commander
        run: |
          gh issue create \
            --title "$TITLE" \
            --label "$LABELS" \
            --body "$BODY"  
